---
- name: Ensure user linuxuser is present
  hosts: all
  become: yes

  tasks:
    - name: Add user linuxuser
      ansible.builtin.user:
        name: linuxuser
        comment: ""
        state: present
        createhome: yes


- name: Ensure user linuxuser is in the correct groups
  hosts: all
  become: yes

  tasks:
    - name: Add user linuxuser to www-data group
      ansible.builtin.user:
        name: linuxuser
        groups: www-data
        append: yes

    - name: Add user linuxuser to sudo group
      ansible.builtin.user:
        name: linuxuser
        groups: sudo
        append: yes

    - name: Add linuxuser to the sudoers file to allow sudo without a password
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^linuxuser'
        line: 'linuxuser ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
