---
- name: Ensure SSH key is present in authorized_keys for user linuxuser
  hosts: all
  become: yes

  vars:
    ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC6234fiTgFDAfvT252Qwersi/0D9rWgc2rPSKl7arUX unchained@sent.as"

  tasks:
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: /home/linuxuser/.ssh
        state: directory
        owner: linuxuser
        group: linuxuser
        mode: '0700'

    - name: Add SSH key to authorized_keys
      ansible.builtin.authorized_key:
        user: linuxuser
        key: "{{ ssh_key }}"
        state: present

