---
- name: Ensure SSH key is present in authorized_keys for user linuxuser
  hosts: all
  become: yes

  vars_files:
  - secret.enc

  tasks:
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: /home/linuxuser/.ssh
        state: directory
        owner: linuxuser
        group: linuxuser
        mode: '0700'

    - name: Add SSH key to authorized_keys
      ansible.builtin.authorized_key:
        user: linuxuser
        key: "{{ item }}"
        state: present
      loop: "{{ ssh_keys }}"

