---
- name: Ensure MySQL is installed
  hosts: all
  become: yes

  tasks:
    - name: Update the apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install MySQL server
      ansible.builtin.apt:
        name: mysql-server
        state: present
        force_apt_get: yes


    - name: Install MySQL Client
      ansible.builtin.apt:
        name: mysql-client
        state: present


    - name: Install Python3 and pip if not already installed
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip

    
